### ISSUE TITLE
How do I delete a number?

### ISSUE THREAD

**Issue by ghost** [benedmunds/CodeIgniter-Twilio#1]
Hi, using this library, is it possible to delete an existing Twilio number?

**Comment by benedmunds** [comment]
Yes you can, the endpoint is documented here:  https://www.twilio.com/docs/api/rest/incoming-phone-numbers#instance-delete

**Comment by mosio** [comment]
You should be able to do that using:

```
$this->twilio->account->incoming_phone_numbers->delete($sid);
```

For example (not tested live, but something like this should work):

```
try {
  $twilio_phone_number = '+15555555555';  
  $nums = $this->twilio->account->incoming_phone_numbers->getIterator(0, 1, array("PhoneNumber" => $twilio_phone_number));
  foreach ($nums as $n) {
    $this->client->account->incoming_phone_numbers->delete($n->sid);
  }
}
catch (Exception $e) {
}
```

**Comment by ghost** [comment]
Thank you both for responding but I have tried that endpoint as follows and it doesn't work, it tells me method not supportd. Here is my code:

$url = '/' . $this->api_version . '/Accounts/' . $this->account_sid . '/IncomingPhoneNumbers.json';

$data = array(
 'PhoneNumber' => $phone_number,
);

return $this->_twilio->request($url, 'DELETE', $data);

**Comment by mosio** [comment]
Delete is not supported on your URL: https://www.twilio.com/docs/api/rest/incoming-phone-numbers#list-delete

You need to call it specifying the incoming phone number's SID in the url: https://www.twilio.com/docs/api/rest/incoming-phone-numbers#instance

My code should work to retrieve this info if you only know the phone number you want to delete, but it does require two api calls to do the work.
