### ISSUE TITLE
Sample for doing Twilio call

### ISSUE THREAD

**Issue by rpparas** [benedmunds/CodeIgniter-Twilio#2]
Hi,

Do you have example lines of code for doing a call, e.g. what's the equivalent of  this PHP code in CodeIgniter:
        $call = $client->account->calls->create(
            $myphonenumber, // The number of the phone initiating the call
            $recipient, // The number of the phone receiving call
            'http://mycallbackurl.com/file.xml', // The URL Twilio will request when the call is answered
        );

**Comment by benedmunds** [comment]
Sorry I don't use or support this library anymore.  You can check the official PHP SDK here: https://github.com/twilio/twilio-php
